---

- name: Create Elasticache alarm
  ec2_metric_alarm:
    state: present
    region: "{{ aws_region }}"
    name: "{{ name }}-{{ metric }}"
    metric: "{{ metric }}"
    namespace: "{{ namespace }}"
    statistic: "{{ statistic }}"
    comparison: "{{ comparison }}"
    threshold: "{{ threshold }}"
    period: "{{ period }}"
    evaluation_periods: "{{ evaluation_periods }}"
    unit: "{{ unit }}"
    description: "{{ description }}"
    dimensions: "{{ dimensions }}"
    alarm_actions: ["{{ sns.sns_arn }}"]